### ISSUE TITLE
Game freezes on level start when adding a subfolder for the music pack.

### ISSUE THREAD

**Issue by TheoDrHashiriya** [cyberc001/DoomDynMus#2]
- Downloaded/Cloned music pack .zip repos from GitHub won't work because the mod won't run if the music pack .zip has a subfolder.

## Reproduction
1. Download any DoomDynMus music pack.
2. Extract to \folder\\.
3. Add that folder to archive.
4. Load the archive with the mod.

#### Alternative
1. Clone any music pack repo from GitHub. [E.g.](https://github.com/TheoDrHashiriya/DMus_Payday/archive/refs/heads/main.zip)
2. Load the archive with the mod.

## Temporary Solution
1. Clone the music pack repo to .zip.
2. Extract the contents of the music pack.
3. Select the contents and add them to archive.
4. Load the archive with the mod.

**Comment by cyberc001** [comment]
The mod got completely rewritten.
Judging from my testing, either cloning a repo or putting contents in a folder inside an archive now doesn't cause issues.
If the issue persists, feel free to reopen the issue.
