### ISSUE TITLE
[SUGGESTION] Doom Classic OST for DDM?

### ISSUE THREAD

**Issue by mattbratt11** [cyberc001/DoomDynMus#3]
Can you add Dynamic versions of Classic Doom MIDIs such as those from Ultimate Doom, Doom 2, Final Doom, PSX Doom, and Doom 64 in the next update for Doom Dynamic Music? If so, that would be nice.

**Comment by FelesNoctis** [comment]
Late response, but:

(A) music pack(s) could be made for this, but keep in mind that classic DOOM music is much less dynamic than many other games, especially the more recent titles. You could effectively make it so any track can be played on any level fairly easily, but if someone wanted to do a switch between ambient and combat music (or even "high combat) it would be a bit more difficult. At the very least it would require someone going through all the songs and grouping them into low and high energy.

**Comment by cyberc001** [comment]
@FelesNoctis is right, this is literally the job for someone to make a music pack.
If someone is willing to combine a whole bunch of Doom OSTs into a music pack, feel free to do so.
DoomDynMus supports every music format that GZDoom supports - internally it just uses S_ChangeMusic(), so MIDIs can work just fine.
