### ISSUE TITLE
VM execution aborted: array access out of bounds

### ISSUE THREAD

**Issue by TheSeeOHZee** [cyberc001/DoomDynMus#5]
### **Console Log**

VM execution aborted: array access out of bounds. Size = 19, current index = 19
Called from DMus_Player.OnTick at DoomDynMus-master.zip:zscript/musplayer.zs, line 195
Called from DMus_Handler.UiTick at DoomDynMus-master.zip:zscript/mushandler.zs, line 58

### **Sourceport Info**
GZDoom v4.7.1 Windows 64bit

### **Load Order**
doom2.wad
DHTP-master.zip
DoomDynMus-master.zip
DMus_DUSK.zip
Project_Brutality-master.zip
CorruptionCards-v3.5a.pk3
Glory_Kill_v27c.pk3
LTP V6.7.pk3
HXRTCHUD-PB3_v8.3RC2e.pk3
simplehudaddons.pk3
D64RTR[v1.5].wad

### **Reproduction**
* Launch load order.
* Go later into the game.
* Die then hit E.
* Console pops up with the error on the log above.

**Comment by TheSeeOHZee** [comment]
Tried a different music selection (DOOM 2016) instead of DUSK and I think the DUSK music addon is probably having issues with certain DOOM 64 Retribution maps or something.

**Comment by cyberc001** [comment]
Completely rewritten the mod.
It should work just fine now, since more sanity checks are performed when parsing old music pack formats.
If the issue persists, feel free to reopen it.
